###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=eloquent
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
        ports:
            - '3301:3306'

    web:
        build: phpdocker/nginx
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './phpdocker/nginx/logs:/var/log/nginx'
        ports:
            - '8082:80'
        links:
            - app

    app:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
